# Generated by Django 5.2.17 on 2026-09-24 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=48)),
                ('aggregate_id', models.CharField(max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormativeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('metadata_revision', models.PositiveBigIntegerField(default=1)),
                ('state', models.CharField(default='empty', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('state', models.CharField(db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('lease', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('worker_id', models.CharField(blank=True, max_length=80)),
                ('result', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('normative_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.normativeset')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.command')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('manifest', models.JSONField()),
                ('manifest_hash', models.CharField(max_length=64)),
                ('attestation', models.JSONField()),
                ('state', models.CharField(default='ready', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('normative_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='knowledge.normativeset')),
            ],
        ),
        migrations.AddField(
            model_name='normativeset',
            name='active_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='knowledge.release'),
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('personal', 'Личная'), ('project', 'Проект'), ('team', 'Команда'), ('organization', 'Организация')], max_length=16)),
                ('acl_revision', models.PositiveBigIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge.scope')),
            ],
        ),
        migrations.AddField(
            model_name='normativeset',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.scope'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'reader'), ('contributor', 'contributor'), ('reviewer', 'reviewer'), ('curator', 'curator'), ('manager', 'manager')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.scope')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(unique=True)),
                ('data', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'personal')), fields=('owner',), name='knowledge_personal_owner'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('scope', 'user'), name='knowledge_scope_user'),
        ),
    ]
