# Generated by Django 5.2.17 on 2026-09-24 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=240)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('storage_key', models.CharField(max_length=160)),
                ('state', models.CharField(default='queued', max_length=16)),
                ('result', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('normative_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='knowledge.normativeset')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge.sourceupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('normative_set', 'sha256'), name='knowledge_source_set_sha')],
            },
        ),
    ]
