# Generated by Django 5.2.17 on 2026-09-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_sourceupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('entries', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_chunks', to='knowledge.sourceupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'sequence'), name='knowledge_source_coverage_chunk')],
            },
        ),
    ]
