# Generated by Django 5.2.17 on 2026-09-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_coveragechunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('entries', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_chunks', to='knowledge.command')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('command', 'sequence'), name='knowledge_analysis_chunk')],
            },
        ),
    ]
