# Generated by Django 5.2.17 on 2026-09-24 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_analysischunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('definition', models.JSONField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.scope')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='knowledge.documentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'revision'), name='knowledge_profile_revision')],
            },
        ),
    ]
