# Generated by Django 5.2.17 on 2026-09-24 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_documentprofile_profilerevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission', models.JSONField()),
                ('state', models.CharField(default='submitted', max_length=32)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('result', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('normative_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_reviews', to='knowledge.normativeset')),
            ],
        ),
    ]
