# Generated by Django 5.2.17 on 2026-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_experiencereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='normativeset',
            name='purpose',
            field=models.CharField(choices=[('normative', 'Нормативы'), ('experience', 'Опыт')], default='normative', max_length=16),
        ),
    ]
