# Generated by Django 5.2.17 on 2026-09-24 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_normativeset_purpose'),
        ('portal', '0012_llmruntime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('pause_requested', models.BooleanField(default=False)),
                ('progress', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_checks', to='portal.batch')),
                ('experience_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge.release')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeFindingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('entries', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_chunks', to='knowledge.knowledgecheck')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'sequence'), name='knowledge_check_finding_chunk')],
            },
        ),
    ]
