# Generated by Django 5.2.17 on 2026-09-27 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_knowledgecheck_knowledgefindingchunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_id', models.UUIDField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('contexts', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(db_index=True, max_length=24)),
                ('profile_key', models.CharField(db_index=True, max_length=80)),
                ('section', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(db_index=True, default='unreviewed', max_length=24)),
                ('latest_analysis', models.BooleanField(db_index=True, default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_cards', to='knowledge.command')),
                ('pending', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='knowledge.command')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.sourceupload')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertCardRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='knowledge.expertcard')),
            ],
        ),
        migrations.AddIndex(
            model_name='expertcard',
            index=models.Index(fields=['source', 'latest_analysis', 'status'], name='expert_source_state'),
        ),
        migrations.AddConstraint(
            model_name='expertcardrevision',
            constraint=models.UniqueConstraint(fields=('card', 'revision'), name='expert_card_revision'),
        ),
    ]
