# Generated by Django 5.2.17 on 2026-09-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_checklogchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=520)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('expert_selected', models.BooleanField(default=False)),
                ('conflict', models.BooleanField(default=False)),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='knowledge.expertcard')),
                ('normative_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glossary_groups', to='knowledge.normativeset')),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500)),
                ('kind', models.CharField(max_length=16)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='glossary_variant', to='knowledge.expertcard')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='knowledge.glossarygroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='glossarygroup',
            constraint=models.UniqueConstraint(fields=('normative_set', 'key'), name='knowledge_glossary_key'),
        ),
    ]
