# Generated by Django 5.2.17 on 2026-09-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0013_glossary_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceupload',
            name='identification',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sourceupload',
            name='identification_revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
