from django.urls import path
from . import views
from . import expert_views as e
from . import trace_views as t
from . import area as a
from . import check_log as log
from . import glossary as g
from . import portable_area as portable
from . import source_identity as source_meta
from . import object_control

urlpatterns=[
    path('areas/<uuid:identity>/objects/<str:kind>/<uuid:object_id>/',object_control.change),
    path('normative-sets/<uuid:set_id>/sources/<uuid:source_id>/identity/',source_meta.edit),
    path('normative-sets/<uuid:set_id>/sources/<uuid:source_id>/identify/',source_meta.identify),
    path('areas/<uuid:identity>/export.json',portable.export),
    path('areas/<uuid:identity>/import/',portable.load),
    path('worker/area-import/',portable.worker_chunk),
    path('areas/<uuid:identity>/glossary/',g.registry),
    path('areas/<uuid:identity>/glossary/<uuid:card_id>/activate/',g.activate),
    path('areas/<uuid:identity>/search/',a.search),
    path('worker/checks/log/',log.receive),
    path('checks/<uuid:job_id>/log.xlsx',log.download,name='knowledge-check-log'),
    path('areas/',a.areas),
    path('areas/<uuid:identity>/',a.area),
    path('areas/<uuid:identity>/profiles/',a.profiles),
    path('areas/<uuid:identity>/profiles/<uuid:profile_id>/delete/',a.remove_profile),
    path('areas/<uuid:identity>/reviews/',a.reviews),
    path('areas/<uuid:identity>/reviews/<uuid:review_id>/',a.review_decision),
    path('trace/links/',t.links),
    path('trace/links/<uuid:identity>/',t.link),
    path('trace/suggest/',t.suggest),
    path('checks/<uuid:job_id>/matrix/',t.matrix),
    path('worker/release-material/',views.worker_release_material),
    path('normative-sets/<uuid:set_id>/releases/<uuid:release_id>/material/',views.release_material),
    path('expert/catalog/',e.catalog),
    path('expert/cards/',e.cards),
    path('expert/cards/<uuid:identity>/',e.card),
    path('expert/cards/<uuid:identity>/versions/<int:number>/',e.revision),
    path('expert/cards/<uuid:identity>/history/',e.history),
    path('expert/sources/<uuid:source_id>/images/',e.images),
    path('checks/',views.checks),
    path('checks/<uuid:job_id>/',views.check_detail),
    path('checks/<uuid:job_id>/findings/',views.check_findings),
    path('worker/checks/<uuid:command_id>/<uuid:job_id>/documents/<int:document_id>/',views.worker_check_file),
    path('worker/checks/progress/',views.worker_check_progress),
    path('worker/checks/findings/',views.worker_check_findings),
    path('commands/<uuid:command_id>/',views.command_detail),
    path('normative-sets/<uuid:set_id>/prepare/',views.prepare_release),
    path('normative-sets/<uuid:set_id>/compare/',views.compare_releases),
    path('normative-sets/<uuid:set_id>/state/',views.set_state),
    path('normative-sets/<uuid:set_id>/revoke/',views.release_revoke),
    path('normative-sets/<uuid:set_id>/experience/publish/',views.experience_publish),
    path('normative-sets/<uuid:set_id>/reviews/',views.review_submit),
    path('normative-sets/<uuid:set_id>/reviews/list/',views.review_list),
    path('reviews/<uuid:review_id>/',views.review_detail),
    path('reviews/<uuid:review_id>/<str:action>/',views.review_decide),
    path('profiles/',views.profiles),
    path('profiles/<uuid:profile_id>/',views.profile_detail),
    path('scopes/',views.scopes),
    path('scopes/<uuid:scope_id>/memberships/',views.membership),
    path('normative-sets/',views.sets),
    path('normative-sets/<uuid:set_id>/',views.detail),
    path('normative-sets/<uuid:set_id>/sources/',views.sources),
    path('normative-sets/<uuid:set_id>/sources/upload/',views.source_upload),
    path('normative-sets/<uuid:set_id>/sources/<uuid:source_id>/',views.source_detail),
    path('normative-sets/<uuid:set_id>/sources/<uuid:source_id>/coverage/',views.source_coverage),
    path('normative-sets/<uuid:set_id>/sources/<uuid:source_id>/download/',views.source_download),
    path('normative-sets/<uuid:set_id>/sources/<uuid:source_id>/retry/',views.source_retry),
    path('normative-sets/<uuid:set_id>/sources/<uuid:source_id>/analysis/',views.source_analysis),
    path('normative-sets/<uuid:set_id>/publish/',views.publish),
    path('snapshots/',views.snapshots),
    path('snapshots/<uuid:snapshot_id>/',views.snapshot),
    path('worker/claim/',views.worker_claim),
    path('worker/authorize/',views.worker_authorize),
    path('worker/events/',views.worker_event),
    path('worker/renew/',views.worker_renew),
    path('worker/coverage/',views.worker_coverage),
    path('worker/analysis/',views.worker_analysis),
    path('worker/fail/',views.worker_fail),
    path('worker/commands/<uuid:command_id>/sources/<uuid:source_id>/',views.worker_source),
]
