# Generated by Django 5.2.17 on 2026-09-16 18:00

import django.db.models.deletion
import portal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основная модель', max_length=80)),
                ('endpoint', models.URLField(blank=True, max_length=500)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('key_encrypted', models.TextField(blank=True)),
                ('context_tokens', models.PositiveIntegerField(default=20480)),
                ('output_tokens', models.PositiveIntegerField(default=6144)),
                ('concurrency', models.PositiveSmallIntegerField(default=1)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(db_index=True, max_length=64)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=240)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('profile', models.CharField(choices=[('chtz', 'Частное техническое задание'), ('tz', 'Техническое задание'), ('oit', 'Описание информационной технологии'), ('other', 'Другой технический документ')], default='chtz', max_length=12)),
                ('checks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('prepared', 'Подготовлен'), ('waiting', 'Ожидает подключения LLM'), ('cancelled', 'Отменён')], default='prepared', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('file', models.FileField(upload_to=portal.models.private_path)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('paragraphs', models.PositiveIntegerField(default=0)),
                ('tables', models.PositiveIntegerField(default=0)),
                ('outline', models.JSONField(default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.batch')),
            ],
        ),
    ]
