# Generated by Django 5.2.17 on 2026-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_reviewfeedback_id_alter_workerrun_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='last_probe',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workerrun',
            name='control',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('prepared', 'Подготовлен'), ('waiting', 'В очереди'), ('preparing', 'Подготовка'), ('running', 'Проверяется'), ('paused', 'Приостановлен'), ('partial', 'Завершён с ограничениями'), ('completed', 'Завершён'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='prepared', max_length=20),
        ),
    ]
