# Generated by Django 5.2.17 on 2026-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_llmconfig_last_probe_workerrun_control_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPresence',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(default='idle', max_length=16)),
                ('heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
