# Generated by Django 5.2.17 on 2026-09-30 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_accessprofile_is_expert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_role',
            field=models.CharField(choices=[('unassigned', 'Роль не задана'), ('target', 'Проверяемый документ'), ('approved_reference', 'Утверждённый эталон')], default='unassigned', max_length=24),
        ),
        migrations.AddField(
            model_name='document',
            name='review_working_file',
            field=models.FileField(blank=True, upload_to='review-sources/'),
        ),
        migrations.AddField(
            model_name='document',
            name='review_working_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='WordReviewProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=160)),
                ('result_version', models.CharField(max_length=64)),
                ('operation', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.batch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.document')),
            ],
        ),
        migrations.CreateModel(
            name='WordReviewExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('state', models.CharField(default='planned', max_length=16)),
                ('snapshot', models.JSONField(default=dict)),
                ('plans', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('artifact', models.FileField(blank=True, upload_to='word-reviews/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_exports', to='portal.batch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'key'), name='word_review_snapshot_key')],
            },
        ),
    ]
