# Generated by Django 5.2.17 on 2026-09-30 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_word_review_exports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='presentation',
            field=models.CharField(choices=[('chat', 'Чат'), ('expert', 'Полный интерфейс')], default='chat', max_length=12),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Светлая'), ('dark', 'Тёмная')], max_length=8),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Новая проверка', max_length=160)),
                ('draft', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='portal.batch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Система')], max_length=12)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.conversation')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'key'), name='unique_chat_message_key')],
            },
        ),
    ]
