# Generated by Django 5.2.17 on 2026-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_accessprofile_presentation_accessprofile_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='review_scope',
            field=models.JSONField(default=dict),
        ),
    ]
